# Generated by Django 5.1.6 on 2025-02-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
